In [ ]:
from os.path import dirname, abspath, join
import pandas as pd
from sklearn import tree
from sklearn.model_selection import train_test_split

from Cleaning import CsvFile

current_dir = dirname(abspath(__file__))

df = CsvFile(join(current_dir, "titanic.csv")) # My Library

In [ ]:
df.view() # if you use pandas, write "df" only

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
data = df.copy()

In [ ]:
data.extract_keywords('Name', inplace = True, use_regex = True, Prefix = r' ([A-Za-z]+)\.') # my library too
data.view()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Prefix
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Rev
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Miss
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Miss
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Mr
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Mr

In [ ]:
data.extract_keywords('Name', inplace = True, use_regex = True, Surname = r'^([^,]+)')
data.view()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Prefix,Surname
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr,Braund
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs,Cumings
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss,Heikkinen
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs,Futrelle
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr,Allen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Rev,Montvila
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Miss,Graham
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Miss,Johnston
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Mr,Behr
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Mr,Dooley

In [ ]:
data.loc[data['Embarked'].isna(), :].view()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Prefix,Surname
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,B28,NaN,Miss,Icard
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0,B28,NaN,Mrs,Stone

In [ ]:
data.fill_missing('Embarked', strategy = 'mode', hierarchy_cols = ['Prefix', 'Surname'], inplace = True)
data.view()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Prefix,Surname
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr,Braund
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs,Cumings
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss,Heikkinen
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs,Futrelle
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr,Allen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Rev,Montvila
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Miss,Graham
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Miss,Johnston
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Mr,Behr
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Mr,Dooley

In [ ]:
data.fill_missing('Age', strategy = 'mean', hierarchy_cols = ['Prefix'], inplace = True)
data.view()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Prefix,Surname
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S,Mr,Braund
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C,Mrs,Cumings
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss,Heikkinen
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S,Mrs,Futrelle
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S,Mr,Allen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S,Rev,Montvila
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S,Miss,Graham
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,21.773973,1,2,W./C. 6607,23.4500,NaN,S,Miss,Johnston
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C,Mr,Behr
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q,Mr,Dooley

In [ ]:
data['cabin_list'] = data['Cabin'].str.split(" ")
data.view()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Prefix,Surname,cabin_list
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S,Mr,Braund,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C,Mrs,Cumings,[C85]
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss,Heikkinen,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S,Mrs,Futrelle,[C123]
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S,Mr,Allen,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S,Rev,Montvila,NaN
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S,Miss,Graham,[B42]
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,21.773973,1,2,W./C. 6607,23.4500,NaN,S,Miss,Johnston,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C,Mr,Behr,[C148]
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q,Mr,Dooley,NaN

In [ ]:
exploded_cabins = data['cabin_list'].explode()

In [ ]:
decks = exploded_cabins.str[0]

data['Highest_Deck'] = decks.groupby(level = 0).min().fillna('Unknown')
data['Lowest_Deck'] = decks.groupby(level = 0).max().fillna('Unknown')

In [ ]:
data.view()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Prefix,Surname,cabin_list,Highest_Deck,Lowest_Deck
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S,Mr,Braund,NaN,Unknown,Unknown
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C,Mrs,Cumings,[C85],C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss,Heikkinen,NaN,Unknown,Unknown
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S,Mrs,Futrelle,[C123],C,C
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S,Mr,Allen,NaN,Unknown,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S,Rev,Montvila,NaN,Unknown,Unknown
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S,Miss,Graham,[B42],B,B
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,21.773973,1,2,W./C. 6607,23.4500,NaN,S,Miss,Johnston,NaN,Unknown,Unknown
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C,Mr,Behr,[C148],C,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q,Mr,Dooley,NaN,Unknown,Unknown

In [ ]:
exploded_numbers = exploded_cabins.str.extract(r'(\d+)')[0].astype(float)

sides = exploded_numbers.mod(2).map({0: 'Port', 1: 'Starboard'})
passenger_sides = sides.dropna().groupby(level = 0).unique()

In [ ]:
data['Ship_Side'] = passenger_sides.str.join(' & ')
data['Ship_Side'] = data['Ship_Side'].fillna('Unknown')

data.view()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Prefix,Surname,cabin_list,Highest_Deck,Lowest_Deck,Ship_Side
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S,Mr,Braund,NaN,Unknown,Unknown,Unknown
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C,Mrs,Cumings,[C85],C,C,Starboard
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss,Heikkinen,NaN,Unknown,Unknown,Unknown
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S,Mrs,Futrelle,[C123],C,C,Starboard
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S,Mr,Allen,NaN,Unknown,Unknown,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S,Rev,Montvila,NaN,Unknown,Unknown,Unknown
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S,Miss,Graham,[B42],B,B,Port
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,21.773973,1,2,W./C. 6607,23.4500,NaN,S,Miss,Johnston,NaN,Unknown,Unknown,Unknown
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C,Mr,Behr,[C148],C,C,Port
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q,Mr,Dooley,NaN,Unknown,Unknown,Unknown

In [ ]:
data['Group_Size'] = data.groupby('Ticket')['Ticket'].transform('count')
data.view()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Prefix,Surname,cabin_list,Highest_Deck,Lowest_Deck,Ship_Side,Group_Size
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S,Mr,Braund,NaN,Unknown,Unknown,Unknown,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C,Mrs,Cumings,[C85],C,C,Starboard,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss,Heikkinen,NaN,Unknown,Unknown,Unknown,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S,Mrs,Futrelle,[C123],C,C,Starboard,2
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S,Mr,Allen,NaN,Unknown,Unknown,Unknown,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S,Rev,Montvila,NaN,Unknown,Unknown,Unknown,1
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S,Miss,Graham,[B42],B,B,Port,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,21.773973,1,2,W./C. 6607,23.4500,NaN,S,Miss,Johnston,NaN,Unknown,Unknown,Unknown,2
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C,Mr,Behr,[C148],C,C,Port,1
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q,Mr,Dooley,NaN,Unknown,Unknown,Unknown,1

In [ ]:
data.drop(['cabin_list', 'Cabin'], axis = 'columns', inplace = True)

In [ ]:
ml_data = data.drop(['PassengerId', 'Surname', 'Prefix', 'Name', 'Ticket', 'Fare'], axis = 'columns').copy()
ml_data.view()

,Survived,Pclass,Sex,Age,SibSp,Parch,Embarked,Highest_Deck,Lowest_Deck,Ship_Side,Group_Size
0,0,3,male,22.000000,1,0,S,Unknown,Unknown,Unknown,1
1,1,1,female,38.000000,1,0,C,C,C,Starboard,1
2,1,3,female,26.000000,0,0,S,Unknown,Unknown,Unknown,1
3,1,1,female,35.000000,1,0,S,C,C,Starboard,2
4,0,3,male,35.000000,0,0,S,Unknown,Unknown,Unknown,1
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,S,Unknown,Unknown,Unknown,1
887,1,1,female,19.000000,0,0,S,B,B,Port,1
888,0,3,female,21.773973,1,2,S,Unknown,Unknown,Unknown,2
889,1,1,male,26.000000,0,0,C,C,C,Port,1
890,0,3,male,32.000000,0,0,Q,Unknown,Unknown,Unknown,1

In [ ]:
ml_data['Sex'] = data['Sex'].map({'male': 0, 'female': 1})
ml_data.view()

,Survived,Pclass,Sex,Age,SibSp,Parch,Embarked,Highest_Deck,Lowest_Deck,Ship_Side,Group_Size
0,0,3,0,22.000000,1,0,S,Unknown,Unknown,Unknown,1
1,1,1,1,38.000000,1,0,C,C,C,Starboard,1
2,1,3,1,26.000000,0,0,S,Unknown,Unknown,Unknown,1
3,1,1,1,35.000000,1,0,S,C,C,Starboard,2
4,0,3,0,35.000000,0,0,S,Unknown,Unknown,Unknown,1
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,0,27.000000,0,0,S,Unknown,Unknown,Unknown,1
887,1,1,1,19.000000,0,0,S,B,B,Port,1
888,0,3,1,21.773973,1,2,S,Unknown,Unknown,Unknown,2
889,1,1,0,26.000000,0,0,C,C,C,Port,1
890,0,3,0,32.000000,0,0,Q,Unknown,Unknown,Unknown,1

In [ ]:
ml_data = pd.get_dummies(ml_data, columns = ['Embarked'], drop_first = True)
ml_data.view()

,Survived,Pclass,Sex,Age,SibSp,Parch,Highest_Deck,Lowest_Deck,Ship_Side,Group_Size,Embarked_Q,Embarked_S
0,0,3,0,22.000000,1,0,Unknown,Unknown,Unknown,1,False,True
1,1,1,1,38.000000,1,0,C,C,Starboard,1,False,False
2,1,3,1,26.000000,0,0,Unknown,Unknown,Unknown,1,False,True
3,1,1,1,35.000000,1,0,C,C,Starboard,2,False,True
4,0,3,0,35.000000,0,0,Unknown,Unknown,Unknown,1,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,0,27.000000,0,0,Unknown,Unknown,Unknown,1,False,True
887,1,1,1,19.000000,0,0,B,B,Port,1,False,True
888,0,3,1,21.773973,1,2,Unknown,Unknown,Unknown,2,False,True
889,1,1,0,26.000000,0,0,C,C,Port,1,False,False
890,0,3,0,32.000000,0,0,Unknown,Unknown,Unknown,1,True,False

In [ ]:
encoded_sides = ml_data['Ship_Side'].str.get_dummies(sep = ' & ').drop('Unknown', axis = 'columns').rename({'Port': 'Side_Port', 'Starboard': 'Side_Starboard'}, axis = 'columns')

In [ ]:
ml_data = pd.concat([ml_data.drop('Ship_Side', axis = 'columns'), encoded_sides], axis = 'columns')

ml_data.view()

,Survived,Pclass,Sex,Age,SibSp,Parch,Highest_Deck,Lowest_Deck,Group_Size,Embarked_Q,Embarked_S,Side_Port,Side_Starboard
0,0,3,0,22.000000,1,0,Unknown,Unknown,1,False,True,0,0
1,1,1,1,38.000000,1,0,C,C,1,False,False,0,1
2,1,3,1,26.000000,0,0,Unknown,Unknown,1,False,True,0,0
3,1,1,1,35.000000,1,0,C,C,2,False,True,0,1
4,0,3,0,35.000000,0,0,Unknown,Unknown,1,False,True,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,0,27.000000,0,0,Unknown,Unknown,1,False,True,0,0
887,1,1,1,19.000000,0,0,B,B,1,False,True,1,0
888,0,3,1,21.773973,1,2,Unknown,Unknown,2,False,True,0,0
889,1,1,0,26.000000,0,0,C,C,1,False,False,1,0
890,0,3,0,32.000000,0,0,Unknown,Unknown,1,True,False,0,0

In [ ]:
ml_data = pd.get_dummies(ml_data, columns = ['Highest_Deck']).drop('Highest_Deck_Unknown', axis = 'columns')
ml_data.drop('Lowest_Deck', axis = 'columns', inplace = True)
ml_data.view()

,Survived,Pclass,Sex,Age,SibSp,Parch,Group_Size,Embarked_Q,Embarked_S,Side_Port,Side_Starboard,Highest_Deck_A,Highest_Deck_B,Highest_Deck_C,Highest_Deck_D,Highest_Deck_E,Highest_Deck_F,Highest_Deck_G,Highest_Deck_T
0,0,3,0,22.000000,1,0,1,False,True,0,0,False,False,False,False,False,False,False,False
1,1,1,1,38.000000,1,0,1,False,False,0,1,False,False,True,False,False,False,False,False
2,1,3,1,26.000000,0,0,1,False,True,0,0,False,False,False,False,False,False,False,False
3,1,1,1,35.000000,1,0,2,False,True,0,1,False,False,True,False,False,False,False,False
4,0,3,0,35.000000,0,0,1,False,True,0,0,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,0,27.000000,0,0,1,False,True,0,0,False,False,False,False,False,False,False,False
887,1,1,1,19.000000,0,0,1,False,True,1,0,False,True,False,False,False,False,False,False
888,0,3,1,21.773973,1,2,2,False,True,0,0,False,False,False,False,False,False,False,False
889,1,1,0,26.000000,0,0,1,False,False,1,0,False,False,True,False,False,False,False,False
890,0,3,0,32.000000,0,0,1,True,False,0,0,False,False,False,False,False,False,False,False

In [ ]:
ml_data['Friends'] = (ml_data['Group_Size'] - ml_data['Parch'] - ml_data['SibSp'] - 1).clip(lower = 0)
ml_data.drop('Group_Size', axis = 'columns', inplace = True)

ml_data.view()

,Survived,Pclass,Sex,Age,SibSp,Parch,Embarked_Q,Embarked_S,Side_Port,Side_Starboard,Highest_Deck_A,Highest_Deck_B,Highest_Deck_C,Highest_Deck_D,Highest_Deck_E,Highest_Deck_F,Highest_Deck_G,Highest_Deck_T,Friends
0,0,3,0,22.000000,1,0,False,True,0,0,False,False,False,False,False,False,False,False,0
1,1,1,1,38.000000,1,0,False,False,0,1,False,False,True,False,False,False,False,False,0
2,1,3,1,26.000000,0,0,False,True,0,0,False,False,False,False,False,False,False,False,0
3,1,1,1,35.000000,1,0,False,True,0,1,False,False,True,False,False,False,False,False,0
4,0,3,0,35.000000,0,0,False,True,0,0,False,False,False,False,False,False,False,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,0,27.000000,0,0,False,True,0,0,False,False,False,False,False,False,False,False,0
887,1,1,1,19.000000,0,0,False,True,1,0,False,True,False,False,False,False,False,False,0
888,0,3,1,21.773973,1,2,False,True,0,0,False,False,False,False,False,False,False,False,0
889,1,1,0,26.000000,0,0,False,False,1,0,False,False,True,False,False,False,False,False,0
890,0,3,0,32.000000,0,0,True,False,0,0,False,False,False,False,False,False,False,False,0

In [ ]:
train_data, test_data = train_test_split(ml_data, test_size = 0.2, random_state = 42)

model = tree.DecisionTreeClassifier(max_depth = 12, random_state = 42) # You could change the parameters or values to show how the final score be affected
model.fit(train_data.drop('Survived', axis = 'columns'), train_data['Survived'])

DecisionTreeClassifier(max_depth=12, random_state=42)

In [ ]:
test_data.head().view()

,Survived,Pclass,Sex,Age,SibSp,Parch,Embarked_Q,Embarked_S,Side_Port,Side_Starboard,Highest_Deck_A,Highest_Deck_B,Highest_Deck_C,Highest_Deck_D,Highest_Deck_E,Highest_Deck_F,Highest_Deck_G,Highest_Deck_T,Friends
709,1,3,0,4.574167,1,1,False,False,0,0,False,False,False,False,False,False,False,False,0
439,0,2,0,31.000000,0,0,False,True,0,0,False,False,False,False,False,False,False,False,0
840,0,3,0,20.000000,0,0,False,True,0,0,False,False,False,False,False,False,False,False,0
720,1,2,1,6.000000,0,1,False,True,0,0,False,False,False,False,False,False,False,False,1
39,1,3,1,14.000000,1,0,False,False,0,0,False,False,False,False,False,False,False,False,0

In [ ]:
model.predict(test_data.drop('Survived', axis = 'columns'))[:5]

array([0, 1, 0, 1, 0])

In [ ]:
model.score(test_data.drop('Survived', axis = 'columns'), test_data['Survived'])

0.7877094972067039

In [ ]:
ml_data['Survived'].value_counts(normalize = True)

Survived
0    0.616162
1    0.383838
Name: proportion, dtype: float64